#Variable: buildConfiguration
#Variable: nugetPackagePattern
#Variable: nugetVersion
#Variable: nugetApiKey
#Variable: nugetService


trigger:
- master
jobs:
- job: Phase_1
  displayName: Build and push NuGet Package
  cancelTimeoutInMinutes: 1
  pool:
    vmImage: ubuntu-latest
  variables:
    buildConfiguration: 'Release'
  steps:
  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'NuGet pack'
    inputs:
      command: 'pack'
      packagesToPack: $(nugetPackagePattern)
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'nugetVersion'

  - script: dotnet nuget push $(Build.ArtifactStagingDirectory)/**/*.nupkg --api-key $(nugetApiKey) --source $(nugetService)  
    displayName: 'Nuget push'

