#Variable: buildConfiguration
#Variable: nugetPackagePattern
#Variable: nugetVersion
#Variable: nugetApiKey
#Variable: nugetService


trigger:
- feature/*
jobs:
- job: Phase_1
  displayName: Build and push NuGet Package
  cancelTimeoutInMinutes: 1
  pool:
    vmImage: ubuntu-latest
  variables:
    buildConfiguration: 'Release'
    GitVersion.SemVer: ''
  
  steps:
  - task: gitversion/setup@0
    displayName: GitVersion
    inputs:
     versionSpec: 'x.x.x'
  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'NuGet pack'
    inputs:
      command: 'pack'
      arguments: '--configuration $(buildConfiguration)'
      packagesToPack: $(nugetPackagePattern)
      nobuild: true
      versioningScheme: 'byEnvVar'      
      versionEnvVar: 'GitVersion.SemVer'

  - script: dotnet nuget push '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg' --api-key $(nugetApiKey) --source $(nugetService)  
    displayName: 'Nuget push'
